language: node_js
node_js:
  - "7"
before_script:
  - "npm install"
script:
  - echo "Antes de la construccion"
  - npm build
  -ls
  
deploy:
  provider: pages
  local -dir: build/
  skip_cleanup: true
  gthub_token: $GITHUB_TOKEN # Set in 
  keep_history: true
  on:
    branch: master
